// <auto-generated />
using System;
using System.Numerics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using billing_system_core.Infrastructure.Persistance;

#nullable disable

namespace billing_system_core.Infrastructure.Migrations
{
    [DbContext(typeof(BillingSystemCoreDBContext))]
    [Migration("20230330065409_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("billing_system_core.Domain.Product.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AssetManagement")
                        .HasColumnType("boolean");

                    b.Property<string>("AvailableAccountTypes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AvailableEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AvailableStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Companies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DecimalQuantity")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExcludedCategories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GlCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ManualPricing")
                        .HasColumnType("boolean");

                    b.Property<float>("MasterAgentCommission")
                        .HasColumnType("real");

                    b.Property<BigInteger>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReservationDuration")
                        .HasColumnType("integer");

                    b.Property<float>("StandardAgentCommission")
                        .HasColumnType("real");

                    b.Property<bool>("StandardAvailability")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("billing_system_core.Domain.ProductCategory.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAssetManagement")
                        .HasColumnType("boolean");

                    b.Property<string>("Companies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OneItemPerCustomer")
                        .HasColumnType("boolean");

                    b.Property<bool>("OneItemPerOrder")
                        .HasColumnType("boolean");

                    b.Property<string>("ParentCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
